out_dir: /kaggle/working/results
metric_best: f1
wandb:
  use: True
  project: HCPGender
  entity: pnvmanh2123-vncert
dataset:
  format: HCP
  name: HCPGender
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  split_mode: random
  split: [0.8, 0.1, 0.1]
  # dir: /project/uvadm/zhenyu/datasets
prep:
  centrality: False
  centrality_types: katz
  centrality_buckets: 100
  neighbors: False
  neighbor_hops: 6
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 60
  enable_ckpt: False
  auto_resume: False
  epoch_resume: 59
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
  num_experts: 3
  learn_rank: True
  learn_rank_start_epoch: 0
  graph_index: True
  captum: False
  gnn_explainer: False
  mamba_interpret: False
  same_order_all_layers: True
  moe_pos_enc: True
gt:
  layer_type: CustomGatedGCN+Mamba_MoE
  n_heads: 4
  dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.0
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.05
  max_epoch: 40
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
seed: 0
test_with_subgraph: True
